### PR TITLE
Pp training program

### PR DESCRIPTION
**Pull request by ppatton35745**
# Training Program List, Create, Details

## Description

Training Program controller displaying list, details, and option to create

## Steps to Test

Click Training in the Nav bar and a list of training should be displayed

Click Details and the details of start and end date and max occupancy should be displayed

Click Create new option and a form with name, dates, and occupancy should be displayed

warning messages should be displayed until all fields are filled out when clicking the create button

Upon successful create the new training should be displayed in the list of training

##### Link to Feature Ticket
#9 #10 (10 partial details only)

### CODE REVIEW

**Comment by awieckert** [comment]
👍 Tested all requested features. Worked successfully.

**Comment by elliot-huck** [comment]
- [ ] Trainings Index should only show a list of all trainings that haven't taken place yet #9 
- [ ] Training model needs to be changed to add Description property #9 
- [ ] bangazon.sql and seed-bangazon.sql need to be changed to reflect new Description property on Training model #9 
- [ ] Create needs to have an input field for the Description property #9 
- [ ] Details need to be accessible by clicking on the Training program itself, not just "Details" link #10 
- [ ] Details view needs to show all Employees attending the training #10

**Comment by awieckert** [comment]
🖕

**Comment by jisie** [comment]
Please make sure to resolve all conflicts so that I can approve the PR.

**Comment by ppatton35745** [comment]
Additional Issues above are being addressed in branch pp-training-program-ec

**Comment by jisie** [comment]
👍

**Pull request merged**
